export const FETCH_FILTERED_CATS_REQUEST =
  'FETCH_FILTERED_CATS_REQUEST';
export const FETCH_FILTERED_CATS_SUCCESS =
  'FETCH_FILTERED_CATS_SUCCESS';
export const FETCH_FILTERED_CATS_FAILURE =
  'FETCH_FILTERED_CATS_FAILURE';
export const CLEAR_CATS = 'CLEAR_CATS';
export const SET_TO_END_OF_PAGE = 'SET_TO_END_OF_PAGE';
export const SET_CURRENT_CAT = 'SET_CURRENT_CAT';
export const GO_BACK_TO_LIST = 'GO_BACK_TO_LIST';
export const SHOW_ERROR = 'SHOW_ERROR';
