export const SET_IMAGE_FILTER = 'SET_IMAGE_FILTER';
export const FETCH_FILTERED_IMAGES_REQUEST =
  'FETCH_FILTERED_IMAGES_REQUEST';
export const FETCH_FILTERED_IMAGES_SUCCESS =
  'FETCH_FILTERED_IMAGES_SUCCESS';
export const FETCH_FILTERED_IMAGES_FAILURE =
  'FETCH_FILTERED_IMAGES_FAILURE';
